version: '3'

services:
    mongdb:
      image: mongo
      container_name: cx_db
      ports:
          - 27017:27017
    
    redis:
      image: redis
      container_name: cx_redis
      ports:
          - 6379:6379
